version: '3.4'

services:
    interest_rate_api:
        build:  .
        command: interest_rate_api
        ports: 
         - 5002:80
        environment:
          ASPNETCORE_ENVIRONMENT: Development
    interest_calculation_api:
        build:  .
        links:
            - interest_rate_api:interest_rate_api
        command: interest_calculation_api
        depends_on:
            - interest_rate_api
        ports: 
         - 5003:80
        environment:
          ASPNETCORE_ENVIRONMENT: Development
          ConnectionStrings__InterestRateApi: http://interest_rate_api
          ConnectionStrings__GitHubProjectUrl: https://github.com/heversonr/softplan-challenge
